chart/urls.py
from django.urls import path, reverse
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('kids/', views.KidListView.as_view(), name='kids'),
    path('kids/<int:pk>', views.KidDetailView.as_view(), name='kid-detail'),
    path('kid/create/', views.KidCreate.as_view(), name='kid-create'),
    path('kids/<int:pk>/update/', views.KidUpdate.as_view(), name='kid-update'),
    path('kids/<int:pk>/delete/', views.KidDelete.as_view(), name='kid-delete'),
    path('rules/', views.RuleListView.as_view(), name='rules'),
    path('rules/<int:pk>', views.RuleDetailView.as_view(), name='rule-detail'),
    path('rule/create/', views.RuleCreate.as_view(), name='rule-create'),
    path('rules/<int:pk>/update', views.RuleUpdate.as_view(), name='rule-update'),
    path('rules/<int:pk>/delete', views.RuleDelete.as_view(), name='rule-delete'),
    path('rule-instances', views.RuleInstanceListView.as_view(), name='rule-instance-list'),
    path('rule-instance/create/', views.RuleInstanceCreate.as_view(success_url='/'),  name='rule-instance-create'),
    # put url to rule instance edit here. Can't find anything on moving a uuid into a url
    path('rule-instance/<uuid:pk>/update', views.RuleInstanceUpdate.as_view()),
]

kidchart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chart/', include('chart.urls')),
    path('', RedirectView.as_view(url='chart/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chart/models.py
from django.db import models
from django.forms import ModelForm
from django.urls import reverse
from django.views.generic.base import HttpResponseRedirect
from django.contrib.auth.models import User
import uuid


# Create your models here.


class Rule(models.Model):
    """
    Model representing a base class for rules. Weight field is how much you want the rule to be worth. The same rule can be applied to multiple kids, and a single kid can be assigned multiple rules.
    """
    name = models.CharField(max_length=50, help_text='Enter rule', default=None)
    weight = models.IntegerField(default=0)
    description = models.TextField(max_length=250, help_text='Enter description of rule')

    class Meta:
        ordering = ['name']

    # methods
    def __str__(self):
        return f'{self.name} \n Points worth: {self.weight} \n Description: {self.description}'

    def get_absolute_url(self):
        """
        url to gain access to one Rule
        """

        return reverse('rule-detail', args=[str(self.id)])


class RuleInstance(models.Model):
    """
    Model representing instances of rules. Instances should be assigned to kids. New rules instances can now be assigned to kids.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this rule')
    rule = models.ForeignKey(Rule, on_delete=models.SET_NULL, null=True)
    kid = models.ForeignKey('Kid', related_name='rules', on_delete=models.SET_NULL, null=True)
    completed = models.BooleanField(default=False, help_text='Is this rule completed?')

    def __str__(self):
        return f'{self.rule.name}, Assigned to: {self.kid.name}, Completed: {self.completed}'



class Kid(models.Model):
    """
    Model representing a base class for kids. Each kid will be represented by name with a primary key. Rules can be assigned to individual kids.
    """
    name = models.CharField(max_length=20, help_text='Enter kid name', default=None)
    points = models.IntegerField(default=0)

    class Meta:
        ordering = ['name']

    # methods
    def __str__(self):
        return f'Name: {self.name}\n Points total: {self.points} \n Rules assigned: {self.rules}'

    def get_absolute_url(self):
        """
        url to gain access to one Kid
        """
    
        return reverse('kid-detail', args=[str(self.id)])

class Reward(models.Model):
    name = models.CharField(max_length=50, help_text='Enter reward', default=None)
    points_needed = models.IntegerField(default=0)
    description = models.TextField(max_length=250, help_text='Enter description of reward')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'Name: {self.name} \n Unlocks at: {self.points_needed} points \n Description: {self.description}'

chart/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from chart.models import Kid, Reward, Rule, RuleInstance
from django.views.generic.base import HttpResponseRedirect
from django.forms import ModelForm
# Create your views here.

@login_required
def index(request):
    """
    view function for site homepage. Stuff below will be subject to change if I don't like how it looks
    """
    kids_list = Kid.objects.all()

    rules_list = Rule.objects.all()

    context = {
        'kids_list' : kids_list,
        'rules_list' : rules_list,
    }

    return render(request, 'index.html', context=context)

class KidListView(generic.ListView):
    model = Kid


class KidDetailView(generic.DetailView):

    model = Kid
    
    # gonna need to set up log in stuff - should just convert to DRF
    def get_queryset(self, **kwargs):
        queryset = RuleInstance.objects.filter(kid=self.name)

    # 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['rule_instance_list'] = RuleInstance.objects.all()

        return context


class KidCreate(CreateView):
    model = Kid
    fields = '__all__'

class KidUpdate(UpdateView):
    model = Kid
    fields = '__all__'

class KidDelete(DeleteView):
    model = Kid
    success_url = reverse_lazy('kids')

class RuleListView(generic.ListView):
    model = Rule

class RuleDetailView(generic.DetailView):
    model = Rule

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['rule_instance_list'] = RuleInstance.objects.all()

        return context


class RuleCreate(CreateView):
    model = Rule
    fields = '__all__'

class RuleUpdate(UpdateView):
    model = Rule
    fields = '__all__'

class RuleDelete(DeleteView):
    model = Rule
    success_url = reverse_lazy('rules')


class RuleInstanceListView(generic.ListView):
    model = RuleInstance


class RuleInstanceCreate(CreateView):
    model = RuleInstance
    fields = '__all__'

class RuleInstanceUpdate(UpdateView):
    model = RuleInstance
    fields = '__all__'
# rule instance update should go here

chart/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Kid Chart!</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'kids' %}">Kids</a></li>
          <li><a href="{% url 'rules' %}">Rules</a></li>
          <li><a href="{% url 'rule-instance-create' %}">Assign a Rule</a></li>
        </ul>
        {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

chart/templates/chart/kid_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Kid</h1>

<p>Are you sure you want to delete {{ kid }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

chart/templates/chart/kid_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ kid.name }}</h1>

  <p><strong>Current Points:</strong> {{ kid.points }}</p> 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Rules</h4>


    {% for rule in rule_instance_list %}
      {% if rule.kid.name == kid.name %}
      <hr>

      <p>
        {{ rule }}
      </p>
      {% endif %}
    {% endfor %}


{% comment %}

def update_view(request, id): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
    # fetch the object related to passed id 
    obj = get_object_or_404(GeeksModel, id = id) 
    # pass the object as instance in form 
    form = GeeksForm(request.POST or None, instance = obj) 
    # save the data from the form and 
    # redirect to detail_view 
    if form.is_valid(): 
        form.save() 
        return HttpResponseRedirect("/"+id) 
    # add form dictionary to context 
    context["form"] = form 
{% endcomment %}

  <button><a href="{{ kid.get_absolute_url }}/update">Create and assign a rule - will eventually leaf to rule instance creation</a></button>

  <button><a href="{{ kid.get_absolute_url }}/delete">Delete this kid</a></button>

  </div>
{% endblock %}

chart/templates/chart/kid_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

chart/templates/chart/kid_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Kids</h1>
  <button><a href="/chart/kid/create/">Add a kid</a></button>
  {% if kid_list %}
  <ul>
    {% for kid in kid_list %}
      <li>
        <a href="{{ kid.get_absolute_url }}">{{ kid.name }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No kids here</p>
  {% endif %}       
{% endblock %}

chart/templates/chart/rule_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Kid</h1>

<p>Are you sure you want to delete {{ rule }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

chart/templates/chart/rule_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ rule.name }}</h1>

  <p><strong>Description:</strong> {{ rule.description }}</p> 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Rules</h4>

    {% for rule in rule.ruleinstance_set.all %}
      <hr>
      <p>
        {{ rule.get_status_display }}
      </p>
      
    {% endfor %}
    <button><a href="{{ rule.get_absolute_url }}/update">Update this rule</a></button>

    <button><a href="{{ rule.get_absolute_url }}/delete">Delete this rule</a></button>
  </div>
{% endblock %}

chart/templates/chart/rule_instance_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>

{% endblock %}

chart/templates/chart/rule_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Rules</h1>
  <button><a href="/chart/rule/create/">Create a rule</a></button>
  {% if rule_list %}
  <ul>
    {% for rule in rule_list %}
      <li>
        <a href="{{ rule.get_absolute_url }}">{{ rule.name }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Add some rules to your database</p>
  {% endif %}       
{% endblock %}

chart/templates/chart/ruleinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>

{% endblock %}

chart/templates/chart/ruleinstance_list.html
{% extends "base_generic.html" %}

{% block content %}
rule instance list loads!
{% endblock %}

chart/templates/chart/ruleinstance_update.html
{% extends "base_generic.html" %}

{% block content %}

rule details!
{% endblock %}

chart/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Welcome to Kid Chart!</h1p>
  <p>Click on the nav bar in the corner to get started</p>
  <p>Here you can:</p>
  <ul>
    <li>
      Add a kid to your account
    </li>
    <li>
      Add a rule to your account
    </li>
    <li>
      Assign to rules to your kids
    </li>
    <li>
      Edit all the above
    </li>
  </ul>
{% endblock %}

chart/templates/rewards.html
{% extends "base_generic.html" %}

chart/templates/rules.html
{% extends "base_generic.html" %}